version: "1.0"

jobs:
  quality:
    executor: local
    commands:
      - crystal spec
    needs:
      - format
      - lint

  format:
    executor: local
    commands:
      - crystal tool format --check

  lint:
    executor: local
    commands:
      - ameba

  docs:
    executor: local
    commands:
      - crystal docs
      - open ./docs/index.html
