name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "0 21 * * *"

jobs:
  quality:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.15.0

      - name: Check code formatting
        run: crystal tool format --check

      - name: Crystal Ameba Linter
        run: docker run -v $(pwd):/src ghcr.io/crystal-ameba/ameba:latest

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
