name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 21 * * *

jobs:
  quality:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.10.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check code formatting
        run: crystal tool format --check

      - name: Crystal Ameba Linter
        run: docker run -t -v $PWD/src:/src veelenga/ameba:v0.14.1

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
